# Generated by Django 3.1 on 2022-07-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_data',
            new_name='created_date',
        ),
    ]
